### PR TITLE
Replace old cwd option with configPath for mjmlconfig support

### PR DESCRIPTION
**Pull request by jskrzypek**
This PR should add/update support for mjmlconfig in v4 once the code is released (I think it should land in 4.1) the mjml PR to track is https://github.com/mjmlio/mjml/pull/1206

### CODE REVIEW

**Comment by attilabuti** [comment]
Thank you for your contribution @jskrzypek!
I will merge this when the next MJML version is released with [mjmlconfig](https://github.com/mjmlio/mjml/pull/1206).

**Comment by thierrymichel** [comment]
Hi, any news about merging this?
Thanks!

**Comment by attilabuti** [comment]
@thierrymichel The mjmlconfig support will come with the next stable MJML version (4.2.0). (The current MJML version is 4.2.0-beta.2.) I will merge it when MJML 4.2.0 released.

**Comment by jskrzypek** [comment]
there are some minor additional changes that were made after they accepted
my PR, the main one relevant to this project is that they changed the name
of the option from "configPath" to "mjmlConfigPath"

**Pull request merged**
